/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.

import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData profile = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bot = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData organise = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qucon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apps = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
